## Eigen Decomposition
#### e: eigen values, v: eigen vectors
e, v = la.eig()

In [12]:
import numpy as np
from scipy import linalg as la

A = np.random.rand(3, 3) * 10
print('A: \n', A, end='\n\n')

# e: Eigenvaluse, v: Eigenvectors
e, v = la.eig(A)
e = np.diag(e)
e = np.real(e)
v = np.real(v)

vt = v.T
v_inv = la.inv(v)

print('v:', v.shape,'\n', v, end='\n\n')
print('v_t:', vt.shape,'\n', vt, end='\n\n')
print('e:', e.shape,'\n', e, end='\n\n')
print('v_inv:', v_inv.shape,'\n', v_inv, end='\n\n')
print(A - np.matmul(np.matmul(v,e),v_inv), end='\n\n')

A: 
 [[ 0.92720479  3.85306926  3.78020518]
 [ 8.4130783   8.87537086  6.83285698]
 [ 7.99326251  6.72391931  6.25468588]]

v: (3, 3) 
 [[-0.29912167 -0.81402244  0.10048087]
 [-0.72898324  0.29349521 -0.69915544]
 [-0.61571881  0.50122653  0.70787376]]

v_t: (3, 3) 
 [[-0.29912167 -0.72898324 -0.61571881]
 [-0.81402244  0.29349521  0.50122653]
 [ 0.10048087 -0.69915544  0.70787376]]

e: (3, 3) 
 [[ 18.09870031   0.           0.        ]
 [  0.          -2.78964176   0.        ]
 [  0.           0.           0.74820298]]

v_inv: (3, 3) 
 [[-0.58388046 -0.65542398 -0.5644713 ]
 [-0.99006906  0.15676944  0.29537641]
 [ 0.19317384 -0.6811015   0.71254782]]

[[ -2.88657986e-15  -7.54951657e-15  -6.21724894e-15]
 [ -3.55271368e-15  -8.88178420e-15  -7.10542736e-15]
 [ -4.44089210e-15  -9.76996262e-15  -6.21724894e-15]]



## Logarithm Matrix
#### Diagonal Matrix D
log_D = matlogDig(D)
#### General Matrix M
log_M = matlog(M)

In [32]:
import numpy as np
import numpy.matlib as npm
from scipy import linalg as la

from math import log10

# example 1
print("# Logarithm Calculation")
print(log10(100))

# example 2
print("\n# Logarithm of Diagonal Matrix\n")
D = np.diag((1, 7, 3))
def matlogDig(k):    
    n = k.shape[0]
    if n!=k.shape[1]:
        print("Only Square Matrix!")
    ret_k = npm.zeros((n,n))    
    for i in range(n):
        ret_k[i,i] = log10(k[i,i])
    return ret_k
log_D = matlogDig(D)
print("Original Matrix: ")
print(D)
print("\nLog Matrix : ")
print(log_D)

# example 3
print("\n# Logarithm of General Matrix\n")
M = np.array([[1, 2, 3],[2, 5, 6], [3, 6, 9]])
# M = np.random.rand(3, 3)
def matlog(m):    
    n = m.shape[0]
    if n!=m.shape[1]:
        print("Only Square Matrix!")
        return np.zeros((m.shape[0],m.shape[1]))
    ret_m = npm.zeros((n,n))
    e, v = la.eig(m)
    e = np.real(e)
    e = np.diag(e)
    log_e = matlogDig(e)
    ret_m =  np.matmul(np.matmul(v,log_e),la.inv(v))
    return ret_m
log_M = matlog(M)
print("Original Matrix: ")
print(M)
print("\nLog Matrix : ")
print(log_M)


# Logarithm Calculation
2.0

# Logarithm of Diagonal Matrix

Original Matrix: 
[[1 0 0]
 [0 7 0]
 [0 0 3]]

Log Matrix : 
[[ 0.          0.          0.        ]
 [ 0.          0.84509804  0.        ]
 [ 0.          0.          0.47712125]]

# Logarithm of General Matrix

Original Matrix: 
[[1 2 3]
 [2 5 6]
 [3 6 9]]

Log Matrix : 
[[-14.54476696   0.19273162   5.09522716]
 [  0.19273162   0.25908547   0.57819486]
 [  5.09522716   0.57819486  -0.95749453]]


## Get JN (Constant Matrix)
#### JN(n)

In [38]:
import numpy as np

n = 5
def JN(n):
    return (1/(n-1))*(np.eye(n) -  (1/(n-1))*np.ones((n,n)))
print(JN(n))

[[ 0.1875 -0.0625 -0.0625 -0.0625 -0.0625]
 [-0.0625  0.1875 -0.0625 -0.0625 -0.0625]
 [-0.0625 -0.0625  0.1875 -0.0625 -0.0625]
 [-0.0625 -0.0625 -0.0625  0.1875 -0.0625]
 [-0.0625 -0.0625 -0.0625 -0.0625  0.1875]]


## Covariance Matrix

In [39]:
n = 5
h1 = np.matrix([i for i in range(10) ])
h = np.matrix([[i for i in range(10)] for j in range(n)])

h1 = h1.reshape((1,-1))
print(h1.shape)
def cov(H):
    return np.transpose(H)*JN(H.shape[0])*H
print(cov(h))


(1, 10)
[[  0.       0.       0.       0.       0.       0.       0.       0.       0.
    0.    ]
 [  0.      -0.3125  -0.625   -0.9375  -1.25    -1.5625  -1.875   -2.1875
   -2.5     -2.8125]
 [  0.      -0.625   -1.25    -1.875   -2.5     -3.125   -3.75    -4.375
   -5.      -5.625 ]
 [  0.      -0.9375  -1.875   -2.8125  -3.75    -4.6875  -5.625   -6.5625
   -7.5     -8.4375]
 [  0.      -1.25    -2.5     -3.75    -5.      -6.25    -7.5     -8.75
  -10.     -11.25  ]
 [  0.      -1.5625  -3.125   -4.6875  -6.25    -7.8125  -9.375  -10.9375
  -12.5    -14.0625]
 [  0.      -1.875   -3.75    -5.625   -7.5     -9.375  -11.25   -13.125
  -15.     -16.875 ]
 [  0.      -2.1875  -4.375   -6.5625  -8.75   -10.9375 -13.125  -15.3125
  -17.5    -19.6875]
 [  0.      -2.5     -5.      -7.5    -10.     -12.5    -15.     -17.5    -20.
  -22.5   ]
 [  0.      -2.8125  -5.625   -8.4375 -11.25   -14.0625 -16.875  -19.6875
  -22.5    -25.3125]]


## Pseudo Inverse
#### Right Pseudo Inverse (r<c)
rps()
#### Left Pseudo Inverse (r>c)
lps()

In [40]:
from scipy import linalg as la
import numpy as np
rrccc = np.matrix([[1, 2, 3], [3, 2, 1]])
rrrcc = np.transpose(rrccc)
def rps(A):
    A_tr = np.transpose(A)
    return np.matmul(A_tr,la.inv(np.matmul(A,A_tr)))
def lps(A):
    A_tr = np.transpose(A)
    return np.matmul(la.inv(np.matmul(A_tr,A)),A_tr)

print(np.matmul(rrccc,rps(rrccc)))
print(np.matmul(lps(rrrcc),rrrcc))


[[  1.00000000e+00   1.11022302e-16]
 [ -1.66533454e-16   1.00000000e+00]]
[[  1.00000000e+00  -1.11022302e-16]
 [  0.00000000e+00   1.00000000e+00]]


## Get Affinity
LEM(C1, C2)

In [44]:
import numpy as np
from scipy import linalg as la
n = 5
def normF(m):
    return np.matmul(np.transpose(m),m)
h1 = np.matrix([[10-i for i in range(10)] for j in range(n)])
h2 = np.matrix([[i for i in range(10)] for j in range(n)])

print(cov(h1))
h1_mat = matlog(cov(h1))
h2_mat = matlog(cov(h2))

def LEM(c1, c2):
    return normF(c1-c2)

print( LEM(h1_mat, h2_mat) )

[[-31.25   -28.125  -25.     -21.875  -18.75   -15.625  -12.5     -9.375
   -6.25    -3.125 ]
 [-28.125  -25.3125 -22.5    -19.6875 -16.875  -14.0625 -11.25    -8.4375
   -5.625   -2.8125]
 [-25.     -22.5    -20.     -17.5    -15.     -12.5    -10.      -7.5     -5.
   -2.5   ]
 [-21.875  -19.6875 -17.5    -15.3125 -13.125  -10.9375  -8.75    -6.5625
   -4.375   -2.1875]
 [-18.75   -16.875  -15.     -13.125  -11.25    -9.375   -7.5     -5.625
   -3.75    -1.875 ]
 [-15.625  -14.0625 -12.5    -10.9375  -9.375   -7.8125  -6.25    -4.6875
   -3.125   -1.5625]
 [-12.5    -11.25   -10.      -8.75    -7.5     -6.25    -5.      -3.75
   -2.5     -1.25  ]
 [ -9.375   -8.4375  -7.5     -6.5625  -5.625   -4.6875  -3.75    -2.8125
   -1.875   -0.9375]
 [ -6.25    -5.625   -5.      -4.375   -3.75    -3.125   -2.5     -1.875
   -1.25    -0.625 ]
 [ -3.125   -2.8125  -2.5     -2.1875  -1.875   -1.5625  -1.25    -0.9375
   -0.625   -0.3125]]


ValueError: math domain error